import { test } from "node:test";
import assert from "node:assert/strict";

import { createInitialState, deriveDisplayName } from "../src/domain/defaults.ts";
import { abbreviate, renderStatusView, statusReportLines } from "../src/domain/status.ts";
import { homeViewLines } from "../src/ui/homeview.ts";

test("deriveDisplayName uses the directory basename", () => {
  assert.equal(deriveDisplayName("/tmp/some/my-project"), "my-project");
});

test("createInitialState is deterministic given fixed inputs", () => {
  const a = createInitialState({ displayName: "x", now: "T", projectId: "id" });
  const b = createInitialState({ displayName: "x", now: "T", projectId: "id" });
  assert.deepEqual(a, b);
  assert.equal(a.phase, "research");
  assert.equal(a.revision, 1);
});

test("statusReportLines includes phase, health, revision, and next action", () => {
  const state = createInitialState({ displayName: "demo", now: "T", projectId: "id" });
  const lines = statusReportLines(state).join("\n");
  assert.match(lines, /phase:\s+research/);
  assert.match(lines, /health:\s+unknown/);
  assert.match(lines, /revision:\s+1/);
  assert.match(lines, /next:/);
});

test("renderStatusView is generated-marked and contains key fields", () => {
  const state = createInitialState({ displayName: "My Demo", now: "T", projectId: "id" });
  const view = renderStatusView(state);
  assert.match(view, /GENERATED by NewFang/);
  assert.match(view, /My Demo/);
  assert.match(view, /## Next justified action/);
  assert.ok(view.includes(state.nextAction));
});

test("homeViewLines shows an init hint with no state, and phase/health with state", () => {
  const empty = homeViewLines(null);
  assert.equal(empty.length, 1);
  assert.match(empty[0] as string, /run \/newfang init/);

  const state = createInitialState({ displayName: "demo", now: "T", projectId: "id" });
  const lines = homeViewLines(state);
  assert.equal(lines.length, 2);
  assert.match(lines[0] as string, /phase: research/);
  assert.match(lines[0] as string, /health: unknown/);
});

test("abbreviate truncates long text with an ellipsis", () => {
  assert.equal(abbreviate("short", 72), "short");
  const long = "a".repeat(100);
  const out = abbreviate(long, 10);
  assert.equal(out.length, 10);
  assert.ok(out.endsWith("…"));
});
