import { test } from "node:test";
import assert from "node:assert/strict";

import { createInitialState, deriveDisplayName } from "../src/domain/defaults.ts";
import {
  abbreviate,
  renderStatusView,
  statusReportLines,
  workItemLabel,
} from "../src/domain/status.ts";
import { homeViewLines } from "../src/ui/homeview.ts";
import { createWorkItem, setFocusWorkItem } from "../src/domain/operations.ts";

const T = "2026-07-24T00:00:00.000Z";

function seeded() {
  let s = createInitialState({ displayName: "demo", now: T, projectId: "id" });
  s = createWorkItem(
    s,
    { kind: "task", title: "Active one", status: "in_progress", priority: "high" },
    T,
  );
  s = createWorkItem(s, { kind: "task", title: "Blocked one", status: "blocked" }, T);
  s = setFocusWorkItem(s, "NF-1");
  return s;
}

test("deriveDisplayName uses the directory basename", () => {
  assert.equal(deriveDisplayName("/tmp/some/my-project"), "my-project");
});

test("createInitialState is deterministic and empty", () => {
  const a = createInitialState({ displayName: "x", now: "T", projectId: "id" });
  assert.equal(a.phase, "research");
  assert.equal(a.revision, 1);
  assert.deepEqual(a.workItems, []);
});

test("statusReportLines includes operations, focus, and rationale", () => {
  const lines = statusReportLines(seeded()).join("\n");
  assert.match(lines, /operations:\s+2 open/);
  assert.match(lines, /in-progress NF-1/);
  assert.match(lines, /blocked 1/);
  assert.match(lines, /focus:\s+NF-1/);
});

test("renderStatusView includes the Operations section", () => {
  const view = renderStatusView(seeded());
  assert.match(view, /GENERATED by NewFang/);
  assert.match(view, /## Operations/);
  assert.match(view, /\*\*Open work items\*\*: 2/);
  assert.match(view, /\*\*Blocked\*\*: 1/);
});

test("homeViewLines stays restrained: focus, phase/health, and non-empty counts", () => {
  const empty = homeViewLines(null);
  assert.equal(empty.length, 1);
  assert.match(empty[0] as string, /run \/newfang init/);

  const lines = homeViewLines(seeded(), 80);
  assert.equal(lines.length, 2, "at most two lines");
  assert.match(lines[0] as string, /NewFang · RESEARCH · UNKNOWN/);
  assert.match(lines[0] as string, /Focus NF-1/);
  assert.match(lines[1] as string, /^Next: /);
  assert.match(lines[1] as string, /1 blocked/);
  assert.ok(!(lines[1] as string).includes("risk"), "empty counts are omitted");
  for (const l of lines) assert.ok(Array.from(l).length <= 80, "fits the width");
});

test("homeViewLines degrades safely at narrow widths", () => {
  const lines = homeViewLines(seeded(), 40);
  assert.equal(lines.length, 2);
  for (const l of lines) assert.ok(Array.from(l).length <= 40, `line too wide: ${l}`);
});

test("workItemLabel is compact", () => {
  const s = seeded();
  assert.equal(workItemLabel(s.workItems[0]!), "NF-1 [in_progress] (high) Active one");
});

test("abbreviate truncates long text with an ellipsis", () => {
  assert.equal(abbreviate("short", 72), "short");
  const out = abbreviate("a".repeat(100), 10);
  assert.equal(out.length, 10);
  assert.ok(out.endsWith("…"));
});
