// The global Pi extension shim.
//
// Regression origin: the first version of this shim registered unconditionally. Pi loads BOTH
// `~/.pi/agent/extensions/` and a trusted project's `.pi/extensions/`, so running Pi inside the
// Voila repository loaded the adapter twice and Pi rejected all 30 duplicate tools:
//
//   Error: Failed to load extension ".../voila.ts": Tool "voila_create_work_item" conflicts with ...
//
// The shim now defers to a project-local adapter. These tests hold that behavior in both
// directions, because getting it wrong breaks Pi startup rather than degrading quietly.

import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

// @ts-expect-error - a plain .mjs install script, deliberately without type declarations
import { MARKER, shimSource } from "../scripts/install-global.mjs";

type Registrar = { default: (pi: unknown) => void };

/**
 * Write the generated shim to a real file and import it once. The cwd check lives inside the
 * exported function rather than at module scope, so a single import serves every scenario.
 */
let shimModule: Promise<Registrar> | undefined;
function loadShim(): Promise<Registrar> {
  shimModule ??= (async () => {
    const dir = await mkdtemp(join(tmpdir(), "voila-shim-"));
    const file = join(dir, "voila.ts");
    await writeFile(file, shimSource() as string, "utf8");
    return (await import(pathToFileURL(file).href)) as Registrar;
  })();
  return shimModule;
}

/** Register through the shim with `cwd` in effect, and report what it registered. */
async function registerFrom(cwd: string): Promise<{ commands: string[]; tools: string[] }> {
  const module = await loadShim();
  const commands: string[] = [];
  const tools: string[] = [];
  const previous = process.cwd();
  process.chdir(cwd);
  try {
    module.default({
      registerCommand: (name: string) => commands.push(name),
      registerTool: (tool: { name: string }) => tools.push(tool.name),
      on: () => {},
    });
  } finally {
    process.chdir(previous);
  }
  return { commands, tools };
}

test("the generated shim is marked and carries the deferral guard", () => {
  const source = shimSource() as string;
  assert.match(source, new RegExp(MARKER as string), "identifiable as generated by the script");
  assert.match(
    source,
    /existsSync\(join\(process\.cwd\(\), "\.pi", "extensions", "voila\.ts"\)\)/,
    "the shim checks for a project-local adapter before registering",
  );
  assert.match(source, /import adapter from "/, "the shim loads the checkout's adapter by path");
  // It must not copy the implementation; a single source of truth is the whole point.
  assert.ok(!source.includes("registerVoila"), "the shim delegates rather than reimplementing");
});

test("the shim defers to a project-local adapter instead of double-registering", async () => {
  // Simulate any project that ships its own .pi/extensions/voila.ts — the Voila repo itself does.
  const root = await mkdtemp(join(tmpdir(), "voila-global-local-"));
  await mkdir(join(root, ".pi", "extensions"), { recursive: true });
  await writeFile(
    join(root, ".pi", "extensions", "voila.ts"),
    "export default () => {};\n",
    "utf8",
  );

  const { commands, tools } = await registerFrom(root);
  assert.deepEqual(commands, [], "no command is registered when the project ships its own adapter");
  assert.deepEqual(tools, [], "no tool is registered, so Pi sees no conflict");
});

test("the shim registers the full surface in a project without its own adapter", async () => {
  const root = await mkdtemp(join(tmpdir(), "voila-global-plain-"));

  const { commands, tools } = await registerFrom(root);
  assert.deepEqual(commands, ["voila"], "the command is available everywhere else");
  assert.equal(tools.length, 34, "the full tool surface is registered");
  assert.ok(
    tools.every((name) => name.startsWith("voila_")),
    "every registered tool uses the voila_ prefix",
  );
});

test("a project with an unrelated .pi/extensions directory still gets Voila", async () => {
  // Only a voila.ts specifically should suppress the global shim.
  const root = await mkdtemp(join(tmpdir(), "voila-global-other-"));
  await mkdir(join(root, ".pi", "extensions"), { recursive: true });
  await writeFile(
    join(root, ".pi", "extensions", "other.ts"),
    "export default () => {};\n",
    "utf8",
  );

  const { commands } = await registerFrom(root);
  assert.deepEqual(commands, ["voila"], "an unrelated extension does not suppress Voila");
});
