// Generated PROJECT_BRIEF.md: a concise, non-authoritative summary of current accepted project
// truth, small enough to inject into model context. Pure — no I/O.
// Canonical entities in project.json remain authoritative; this file is a projection.

import { GENERATED_BANNER } from "./status.ts";
import { backlogSummary } from "./operations.ts";
import type { ProjectState } from "./types.ts";

/** Max characters of the brief body, keeping it context-injectable. */
export const BRIEF_SOFT_LIMIT = 6000;

function bullets(lines: string[]): string[] {
  return lines.length ? lines : ["_(none)_"];
}

export function renderProjectBrief(state: ProjectState): string {
  const s = backlogSummary(state);
  const accepted = state.decisions.filter((d) => d.status === "accepted");
  const openAssumptions = state.assumptions.filter((a) => a.status === "open");
  const openRisks = state.risks.filter((r) => r.status === "open");
  const acceptedIntakes = state.intakes.filter((i) => i.status === "accepted");
  const pendingIntake = state.intakes.find((i) => i.status === "review_required");

  const out = [
    GENERATED_BANNER,
    "",
    `# ${state.displayName} — Project Brief`,
    "",
    "_Generated by Voila from canonical state. Non-authoritative: `.voila/project.json` is the source of truth._",
    "",
    `- **Phase**: ${state.phase} · **Health**: ${state.health} · **Revision**: ${state.revision}`,
    `- **Focus**: ${s.focus ? `${s.focus.id} — ${s.focus.title}` : "none"}`,
    "",
    "## Next justified action",
    "",
    state.nextAction,
  ];
  if (state.nextActionRationale) {
    out.push("", `**Why now:** ${state.nextActionRationale}`);
  }

  out.push(
    "",
    "## Key accepted decisions",
    "",
    ...bullets(accepted.slice(0, 12).map((d) => `- \`${d.id}\` ${d.title} — ${d.decision}`)),
    "",
    "## Open assumptions",
    "",
    ...bullets(
      openAssumptions.slice(0, 10).map((a) => `- \`${a.id}\` (${a.confidence}) ${a.statement}`),
    ),
    "",
    "## Open risks",
    "",
    ...bullets(
      openRisks
        .slice(0, 10)
        .map((r) => `- \`${r.id}\` (${r.likelihood}/${r.impact}) ${r.statement}`),
    ),
    "",
    "## Work in flight",
    "",
    ...bullets([
      ...s.inProgress.map((w) => `- \`${w.id}\` (in progress) ${w.title}`),
      ...s.blocked.map(
        (w) => `- \`${w.id}\` (blocked) ${w.title} — ${w.blockedReason ?? "no reason recorded"}`,
      ),
      ...s.readyByPriority
        .slice(0, 5)
        .map((w) => `- \`${w.id}\` (ready, ${w.priority}) ${w.title}`),
    ]),
    "",
    "## Source intakes",
    "",
    ...bullets(
      acceptedIntakes.map(
        (i) =>
          `- \`${i.id}\` ${i.title} (${i.sourceType}: \`${i.sourceRef}\`, sha \`${i.sourceSha256.slice(0, 12)}…\`)`,
      ),
    ),
  );

  if (pendingIntake) {
    out.push(
      "",
      "## Pending review",
      "",
      `- \`${pendingIntake.id}\` ${pendingIntake.title} awaits review (draft revision ${pendingIntake.draftRevision}). Run \`/voila intake review\`.`,
    );
  }

  out.push("");
  return out.join("\n");
}
