// Human-readable projections of canonical state. Pure — no I/O.

import type { ProjectState, WorkItem } from "./types.ts";
import { backlogSummary } from "./operations.ts";

export const GENERATED_BANNER =
  "<!-- GENERATED by NewFang from .newfang/project.json — do not edit by hand. -->";

export function abbreviate(text: string, max = 72): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  if (max <= 1) return clean.slice(0, max);
  return `${clean.slice(0, max - 1)}…`;
}

/** Compact one-line work-item label, e.g. "NF-3 [in_progress] (high) Title". */
export function workItemLabel(item: WorkItem): string {
  return `${item.id} [${item.status}] (${item.priority}) ${item.title}`;
}

/** Lines for the `/newfang status` command output. */
export function statusReportLines(state: ProjectState): string[] {
  const s = backlogSummary(state);
  const inProgress = s.inProgress.length > 0 ? s.inProgress.map((w) => w.id).join(", ") : "none";
  return [
    `NewFang — ${state.displayName}`,
    `  id:        ${state.projectId}`,
    `  phase:     ${state.phase}`,
    `  health:    ${state.health}`,
    `  revision:  ${state.revision}`,
    `  updated:   ${state.updatedAt}`,
    `  operations: ${s.openCount} open · in-progress ${inProgress} · blocked ${s.blocked.length} · open-risks ${s.openRiskCount} · accepted-decisions ${s.acceptedDecisionCount}`,
    `  active:    ${state.activeWorkItemId ?? "none"}`,
    `  next:      ${state.nextAction}`,
  ];
}

/** The generated `.newfang/views/PROJECT_STATUS.md` content. */
export function renderStatusView(state: ProjectState): string {
  const s = backlogSummary(state);
  const inProgress = s.inProgress.length > 0 ? s.inProgress.map((w) => w.id).join(", ") : "none";
  const active = s.active ? `${s.active.id} — ${s.active.title}` : "none";
  return [
    GENERATED_BANNER,
    "",
    `# ${state.displayName} — Project Status`,
    "",
    "_Generated by NewFang. Do not edit; change state through NewFang, which regenerates this file._",
    "",
    `- **Project ID**: \`${state.projectId}\``,
    `- **Phase**: ${state.phase}`,
    `- **Health**: ${state.health}`,
    `- **Revision**: ${state.revision}`,
    `- **Created**: ${state.createdAt}`,
    `- **Updated**: ${state.updatedAt}`,
    "",
    "## Operations",
    "",
    `- **Open work items**: ${s.openCount}`,
    `- **In progress**: ${inProgress}`,
    `- **Blocked**: ${s.blocked.length}`,
    `- **Open risks**: ${s.openRiskCount}`,
    `- **Accepted decisions**: ${s.acceptedDecisionCount}`,
    `- **Active item**: ${active}`,
    "",
    "## Next justified action",
    "",
    state.nextAction,
    "",
  ].join("\n");
}
