// Human-readable projections of canonical state. Pure — no I/O.

import type { ProjectState } from "./types.ts";

/** Marker making the generated status view unmistakably generated. */
export const GENERATED_BANNER =
  "<!-- GENERATED by NewFang from .newfang/project.json — do not edit by hand. -->";

export function abbreviate(text: string, max = 72): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  if (max <= 1) return clean.slice(0, max);
  return `${clean.slice(0, max - 1)}…`;
}

/** Lines for the `/newfang status` command output. */
export function statusReportLines(state: ProjectState): string[] {
  return [
    `NewFang — ${state.displayName}`,
    `  id:        ${state.projectId}`,
    `  phase:     ${state.phase}`,
    `  health:    ${state.health}`,
    `  revision:  ${state.revision}`,
    `  updated:   ${state.updatedAt}`,
    `  next:      ${state.nextAction}`,
  ];
}

/** The generated `.newfang/views/PROJECT_STATUS.md` content. */
export function renderStatusView(state: ProjectState): string {
  return [
    GENERATED_BANNER,
    "",
    `# ${state.displayName} — Project Status`,
    "",
    "_Generated by NewFang. Do not edit; change state through NewFang, which regenerates this file._",
    "",
    `- **Project ID**: \`${state.projectId}\``,
    `- **Phase**: ${state.phase}`,
    `- **Health**: ${state.health}`,
    `- **Revision**: ${state.revision}`,
    `- **Created**: ${state.createdAt}`,
    `- **Updated**: ${state.updatedAt}`,
    "",
    "## Next justified action",
    "",
    state.nextAction,
    "",
  ].join("\n");
}
