// Generated UNDERSTANDING.md from a structured draft. Pure — no I/O.
// This is a review artifact: it separates what the source states from what the model inferred, and
// states exactly what applying the intake would change. It is never authoritative.

import { GENERATED_BANNER } from "./status.ts";
import type { Finding, IntakeDraft, SourceReference } from "./intake.ts";
import { blockingConflicts, findingsByCategory, modelInferences } from "./intake.ts";
import type { ApplySummary } from "./apply.ts";
import { applySummaryLines } from "./apply.ts";
import type { IntakeRecord } from "./types.ts";

export function formatSourceRef(ref: SourceReference): string {
  if (ref.startLine !== undefined) {
    return ref.endLine !== undefined && ref.endLine !== ref.startLine
      ? `L${ref.startLine}-${ref.endLine}`
      : `L${ref.startLine}`;
  }
  if (ref.marker) return ref.marker;
  if (ref.excerpt) return `"${ref.excerpt.slice(0, 40)}"`;
  return "(no reference)";
}

function findingLine(f: Finding): string {
  const refs = f.sourceRefs.map(formatSourceRef).join(", ");
  const provenance = f.origin === "model_inference" ? "model inference" : refs || "source";
  const confidence = f.confidence ? `, confidence ${f.confidence}` : "";
  return `- ${f.statement} _(${f.id}; ${provenance}${confidence})_`;
}

function section(title: string, lines: string[]): string[] {
  return [`## ${title}`, "", ...(lines.length ? lines : ["_(none)_"]), ""];
}

export function renderUnderstanding(
  intake: IntakeRecord,
  draft: IntakeDraft,
  summary: ApplySummary,
): string {
  const cat = (c: Parameters<typeof findingsByCategory>[1]) =>
    findingsByCategory(draft, c).map(findingLine);
  const blocking = blockingConflicts(draft);
  const inferences = modelInferences(draft);

  const out: string[] = [
    GENERATED_BANNER,
    "",
    `# Understanding Check — ${intake.id}`,
    "",
    `_Generated by Voila from the structured draft. Not authoritative: canonical project truth changes only when you accept and apply this intake._`,
    "",
    `- **Source**: ${intake.title}`,
    `- **Type**: ${intake.sourceType}`,
    `- **Reference**: \`${intake.sourceRef}\``,
    `- **SHA-256**: \`${intake.sourceSha256.slice(0, 12)}…\``,
    `- **Draft revision**: ${draft.draftRevision}`,
    `- **Status**: ${intake.status}`,
    "",
    "## Objective",
    "",
    draft.objective,
    "",
    ...section("Locked decisions", cat("locked_decision")),
    ...section("Proposed decisions", cat("proposed_decision")),
    ...section("Constraints", cat("constraint")),
    ...section("Requirements", cat("requirement")),
    ...section("Acceptance criteria", cat("acceptance_criterion")),
    ...section("Open questions", cat("open_question")),
    ...section("Assumptions", cat("assumption")),
    ...section("Risks", cat("risk")),
    ...section("Non-goals", cat("non_goal")),
    ...section("Evidence and supporting context", [...cat("evidence"), ...cat("example")]),
  ];

  out.push(
    ...section(
      "Proposed work items",
      draft.proposedWorkItems.map(
        (w) =>
          `- **${w.kind}** ${w.title}${w.priority ? ` (${w.priority})` : ""} _(from ${w.sourceFindingIds.join(", ")})_`,
      ),
    ),
  );

  out.push(
    ...section(
      "Conflicts",
      draft.conflicts.map(
        (c) =>
          `- **${c.severity}**${c.requiresUserResolution ? " (needs your resolution)" : ""}: ${c.explanation} _(${c.findingIds.join(", ")})_`,
      ),
    ),
  );

  out.push(
    ...section(
      "Model inferences (not stated by the source)",
      inferences.map((f) => `- ${f.statement} _(${f.id})_`),
    ),
  );

  if (draft.possibleDuplicates?.length) {
    out.push(
      ...section(
        "Possible duplicates (not merged automatically)",
        draft.possibleDuplicates.map(
          (d) => `- ${d.kind} \`${d.draftRef}\` may duplicate \`${d.existingId}\`: ${d.reason}`,
        ),
      ),
    );
  }

  out.push("## What applying this intake will change", "");
  if (blocking.length > 0) {
    out.push(
      `**Apply is blocked**: ${blocking.length} conflict(s) require your resolution first.`,
      "",
    );
  }
  out.push(...applySummaryLines(summary), "");

  if (draft.reviewNotes) {
    out.push("## Reviewer notes from the Steward", "", draft.reviewNotes, "");
  }

  return out.join("\n");
}
