#!/usr/bin/env node
// Install (or remove) Voila as a GLOBAL Pi extension.
//
// Pi loads extensions from two places: `~/.pi/agent/extensions/` (global, every session) and
// `.pi/extensions/` (project-local, only after the project is trusted). Voila lives project-local in
// its own repository, which is why it cannot be used on other projects out of the box.
//
// This writes one small shim into the global directory that re-exports this checkout's adapter. It
// does NOT copy the code: there is one source of truth, and `git pull` here updates every project.
//
//   node scripts/install-global.mjs            # install
//   node scripts/install-global.mjs --status   # report what is installed
//   node scripts/install-global.mjs --remove   # uninstall
//
// Reversible at any time: the install is a single file, and --remove deletes it.
//
// Note on state: Voila's canonical state stays per-project in `.voila/`. A global install changes
// only where the *code* is loaded from. In a project with no `.voila/`, the widget shows the
// `/voila init` hint and nothing is created until you ask for it.

import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync, realpathSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ADAPTER = join(REPO_ROOT, ".pi", "extensions", "voila.ts");
const GLOBAL_DIR = join(homedir(), ".pi", "agent", "extensions");
const SHIM = join(GLOBAL_DIR, "voila.ts");

export const MARKER = "voila:global-shim";
export const GLOBAL_SHIM_PATH = SHIM;

export function shimSource() {
  return `// ${MARKER}
// Generated by scripts/install-global.mjs in the Voila repository. Do not edit by hand.
//
// This loads the adapter from the Voila checkout so every Pi session gets Voila, while keeping a
// single source of truth. Canonical state stays per-project in .voila/.
//
// Source checkout: ${REPO_ROOT}
// Remove with:     node ${join(REPO_ROOT, "scripts", "install-global.mjs")} --remove

import { existsSync } from "node:fs";
import { join } from "node:path";
import adapter from ${JSON.stringify(ADAPTER)};

// Pi loads BOTH ~/.pi/agent/extensions/ and a trusted project's .pi/extensions/. A project that
// ships its own Voila adapter — the Voila repository itself, most obviously — would otherwise
// register the same command and all 30 tools twice, and Pi rejects the duplicates. Defer to the
// project's copy: it is the one the project chose, and it may be a different version.
export default function voilaGlobal(pi) {
  if (existsSync(join(process.cwd(), ".pi", "extensions", "voila.ts"))) return;
  adapter(pi);
}
`;
}

export async function status() {
  const lines = [];
  lines.push(`checkout: ${REPO_ROOT}`);
  lines.push(`adapter:  ${ADAPTER} ${existsSync(ADAPTER) ? "(present)" : "(MISSING)"}`);
  lines.push(`global:   ${SHIM}`);

  if (!existsSync(SHIM)) {
    lines.push("status:   not installed");
    return { installed: false, lines };
  }
  const contents = await readFile(SHIM, "utf8");
  if (!contents.includes(MARKER)) {
    lines.push("status:   a DIFFERENT voila.ts exists here and was not written by this script");
    return { installed: "foreign", lines };
  }
  const pointsHere = contents.includes(JSON.stringify(ADAPTER));
  lines.push(
    pointsHere
      ? "status:   installed, pointing at this checkout"
      : "status:   installed, but pointing at a DIFFERENT checkout (re-run to repoint)",
  );
  return { installed: true, lines };
}

async function install() {
  if (!existsSync(ADAPTER)) {
    throw new Error(`Cannot find the Voila adapter at ${ADAPTER}. Run this from a Voila checkout.`);
  }
  const current = await status();
  if (current.installed === "foreign") {
    throw new Error(
      `${SHIM} already exists and was not written by this script. Inspect it and move it aside before installing.`,
    );
  }
  await mkdir(GLOBAL_DIR, { recursive: true });
  await writeFile(SHIM, shimSource(), "utf8");
  return [
    `Installed ${SHIM}`,
    `  -> ${ADAPTER}`,
    "",
    "Every Pi session now loads Voila. In a project with no .voila/, the widget shows the",
    "/voila init hint and nothing is created until you ask for it.",
    "",
    `Remove with: node ${join(REPO_ROOT, "scripts", "install-global.mjs")} --remove`,
  ];
}

async function remove() {
  if (!existsSync(SHIM)) return [`Nothing to remove: ${SHIM} does not exist.`];
  const contents = await readFile(SHIM, "utf8");
  if (!contents.includes(MARKER)) {
    throw new Error(
      `Refusing to delete ${SHIM}: it was not written by this script. Remove it yourself if you are sure.`,
    );
  }
  await rm(SHIM);
  return [`Removed ${SHIM}`, "Voila is now project-local again."];
}

/** Only run the CLI when invoked directly, so tests can import shimSource() safely. */
function invokedDirectly() {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}

if (invokedDirectly()) {
  const arg = process.argv[2];
  try {
    if (arg === "--status") {
      console.log((await status()).lines.join("\n"));
    } else if (arg === "--remove") {
      console.log((await remove()).join("\n"));
    } else if (arg === undefined || arg === "--install") {
      console.log((await install()).join("\n"));
    } else {
      console.error(`Unknown argument: ${arg}. Use --install, --status, or --remove.`);
      process.exit(2);
    }
  } catch (error) {
    console.error(`${error.message}`);
    process.exit(1);
  }
}
